steps:

- name: gcr.io/cloud-builders/mvn:3.5.0-jdk-8
  volumes:
  - name: m2
    path: /root/.m2/
  args: ['-X', '-B', 'clean', 'install']

- name: gcr.io/cloud-builders/mvn:3.5.0-jdk-8
  volumes:
  - name: m2
    path: /root/.m2
  entrypoint: bash
  dir: /root/.m2/repository
  args:
  - -c
  - ls -la