substitutions:
  _IMAGE_NAME: cloud-build-demo # Configure this
  _GCS_CACHE_BUCKET: cloud-build-demo

steps:

# Load the cache from GCS if they exist
- name: gcr.io/cloud-builders/gsutil
  dir: /root
  entrypoint: bash
  args:
  - -c
  - |
    (
      gsutil cp gs://${_GCS_CACHE_BUCKET}/m2-cache.tar.gz /tmp/m2-cache.tar.gz &&
      tar -xzf /tmp/m2-cache.tar.gz
    ) || echo 'Cache not found'
  volumes:
  - name: user.home
    path: /root

- name: gcr.io/cloud-builders/mvn:3.5.0-jdk-8
  args: ['clean', 'install', 'jib:build', '-Dimage=eu.gcr.io/${PROJECT_ID}/${_IMAGE_NAME}']
  volumes:
  - name: user.home
    path: /root

- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - run
  - --image=eu.gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest
  - --location=europe-west6-a
  - --cluster=cloud-build-demo
  - --expose=8080

  # Cache the .m2 folder to GCS
- name: gcr.io/cloud-builders/gsutil
  dir: /root
  entrypoint: bash
  args:
  - -c
  - |
    tar -czf /tmp/m2-cache.tar.gz .m2 &&
    gsutil cp /tmp/m2-cache.tar.gz gs://${_GCS_CACHE_BUCKET}/m2-cache.tar.gz
  volumes:
  - name: user.home
    path: /root

- name: gcr.io/cloud-builders/curl
  args:
  - -X
  - POST
  - -H
  - 'Content-type: application/json'
  - --data
  - '{"text":"New deployment done! --> http://34.65.71.251:8080/"}'
  - https://hooks.slack.com/services/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