substitutions:
  _IMAGE_NAME: cloud-build-demo # Configure this
  _GCS_CACHE_BUCKET: cloud-build-demo

steps:

# load the cache from GCS if it exists
- name: gcr.io/cloud-builders/gsutil
  dir: /root
  entrypoint: bash
  args:
  - -c
  - |
    (
      gsutil cp gs://${_GCS_CACHE_BUCKET}/m2-cache.tar.gz /tmp/m2-cache.tar.gz &&
      tar -xzf /tmp/m2-cache.tar.gz
    ) || echo 'Cache not found'
  volumes:
  - name: m2
    path: /root/.m2/


- name: gcr.io/cloud-builders/mvn:3.5.0-jdk-8
  id: build
  args: ['clean', 'install', 'jib:build', '-Dimage=eu.gcr.io/${PROJECT_ID}/${_IMAGE_NAME}']
  volumes:
  - name: m2
    path: /root/.m2/

# cache the /root/.m2 folder and upload it to GCS bucket
- name: gcr.io/cloud-builders/gsutil
  waitFor:
  - build
  dir: /root
  entrypoint: bash
  args:
  - -c
  - |
    tar -czf /tmp/m2-cache.tar.gz .m2 &&
    gsutil cp /tmp/m2-cache.tar.gz gs://${_GCS_CACHE_BUCKET}/m2-cache.tar.gz
  volumes:
  - name: m2
    path: /root/.m2/

# deploy to GKE
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  waitFor:
  - build
  args:
  - run
  - --image=eu.gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest
  - --location=europe-west6-a
  - --cluster=cloud-build-demo
  - --expose=8080

# send notification to slack
- name: gcr.io/cloud-builders/curl
  args:
  - -X
  - POST
  - -H
  - 'Content-type: application/json'
  - --data
  - '{"text":"New deployment done! --> http://34.65.110.195:8080/"}'
  - https://hooks.slack.com/services/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
